[build]
  command = "npm --workspace FundMint_frontend run build"
  publish = "src/FundMint_frontend/dist/client"

[build.environment]
  DFX_VERSION = "0.25.0" # Use the version you need

[[plugins]]
  package = "@netlify/plugin-functions-install-corepack"

[context.production]
  environment = { DFX_VERSION = "0.25.0" }
